Add AArch64 support
Homebrew/glibc-bootstrap pull request #31
Opened 2024-11-16 23:11 UTC by ZhongRuoyu

This brings AArch64 support and allows us to build binaries for bootstrapping glibc on any AArch64 Linux system.

The newly added AArch64 image is based on `centos:7` as it ships glibc 2.17, the first glibc release to support AArch64 [^1].

I've also bumped most of the tools to a newer version that builds without additional patches/hacks. Notably:
- GCC is still on 9.5.0 because it still works, and later versions (that I tested) don't build on Debian Wheezy (the x86_64 image) because the host GCC is too old.
- Python is not on 3.12 or 3.13 because `<stdatomic.h>` is needed but not provided by Debian Wheezy's host toolchain.

The changes here have been tested on both architectures. The binaries built here can support building `glibc` 2.35 in `centos:7` on AArch64 Linux.

[^1]: https://sourceware.org/glibc/wiki/Release/2.17

2024-11-17 08:44 UTC, MikeMcQuaid requested changes

2024-11-17 08:44 UTC, MikeMcQuaid commented on .github/workflows/build.yml
> +          # TODO: add aarch64 when available
Sorry, I'd rather we didn't add `aarch64` in here until we have CI to test it (and same for Portable Ruby).

2024-11-17 18:36 UTC, Bo98 commented
LGTM in general.

I'm happy to either:
- Merge most changes here except the first commit then open a second PR with that, or;
- Hold the whole PR until we're ready for arm64

GitHub Actions arm64 support ETA is early 2025 (delayed from Q4 2024).

2024-11-17 22:08 UTC, ZhongRuoyu commented
> Merge most changes here except the first commit then open a second PR with that (given the other commits are architecture agnostic and are just version bumps etc)

Given the branch name, existing discussions, etc. of this PR, let me do the opposite: I split the architecture agnostic changes into #32.

2024-11-18 09:15 UTC, ZhongRuoyu commented
> Is AArch64 == arm64 on Linux? If so: to avoid confusion: can we try to always call it the same thing 😅.

Yes, they both refer to 64-bit ARM but AArch64 is more commonly used in Linux land (`uname -m` returns `aarch64` as opposed to `arm64` on macOS). Bottles for arm64 Linux are identified by `aarch64_linux` too. I'll try to disambiguate this in the future!

2024-11-18 09:25 UTC, MikeMcQuaid commented
@ZhongRuoyu Thanks for explaining! Thought this was adding Another Linux ARM 😁

2024-11-18 14:46 UTC, Bo98 commented
Yeah we've yet to technically make aarch64 == arm64 in Homebrew/brew code. It just happens to work given most systems agree on the naming and we haven't needed to worry about compatibility of things between incompatible systems (macOS and Linux).

2025-01-17 00:21 UTC, ZhongRuoyu commented
It worked! :tada:

Actionlint failure probably needs https://github.com/rhysd/actionlint/pull/503.

x86_64 CI was not running?

2025-01-17 06:48 UTC, Bo98 commented on .github/workflows/build.yml
>          include:
```suggestion
        arch:
          - x86_64
          - aarch64
        include:
```

should fix CI. `include` doesn't like it when there's no overlap between itself and what's outside.

2025-01-17 12:36 UTC, MikeMcQuaid reviewed
Nice work so far!

2025-01-21 00:35 UTC, Bo98 approved these changes

2025-01-24 15:07 UTC, MikeMcQuaid approved these changes
Looks good to ship, thanks!

2025-02-03 20:21 UTC, merged